language: python
python:
  - "3.5"
# command to install dependencies
install: 
  - "pip3 install https://github.com/Capitains/HookTest/archive/console.zip" 
# command to run tests
script: hooktest --scheme epidoc --workers 3 --travis --countword ./
