language: python
python:
- '3.5'
matrix:
  allow_failures:
    - python: '3.5'
install:
- pip3 install https://github.com/Capitains/HookTest/archive/console.zip
script: hooktest --scheme epidoc --workers 3 --travis --countword ./
before_deploy:
- hooktest-build --travis ./
- tar -cf release.tar.gz ./
deploy:
  provider: releases
  api_key:
    secure: ubd/rbV+wiDsN1m4QFwI1Bu8i5/SolcGXDbWzViOKLJRfn0TLHSs/ko02Klt6nDyTn7uN3S//RtFRPP4YrnnoEsv5Vv/hsXjB43cm2Qvk7Y3kVsN4eWYvWkImQM0VWfbEal/dfctLQ7dNVl9xkX6N9kStXU4eqJwRgv1+INfhserAc67RHc+916WW3DWZmvC+QoxuV4XANtA8pjmXXnZ8bH2T7XGcKmqoUkO1NKRmz5ZseSftdBQ6TirUOl3hZHRObp6CGRfHiFe1u2nrZESq4qhirir0yITCuWb/+c2vm5EcjC6AM/IQ6hzKWJeu3rm9EyHblkgVit6irDmZvvCs5MXCtYO1A8kUSt/S1zFFExB5oUh9uMDz9Xc5GmcmYsGhMlATVkxgdl/Tn3iZ+6QF+tn+mTMn7NxrAFpS5v9iLbx29j4sPEBJU9fD9WmvyrjRgwxAj7kjEzpFwzkE40B+1IHXKxYK/4zW9WoHPbjwZoqyTYRllJkryfcIJLnY4PkBmiRYxjGPjZBrtq31BPRFjLidnTQxXnh29v4//gHWCVLqdjfuFRVEqqqzs2iS4QgqrUbcMNRk3Ccfqt8b6yyoywa1lZRF5xS+YnNX/G/G1/cCnHgK7dUpSw8VacqCSLSP3R+iY9amFvsi+o7LDpFLtHcz6x/nsgCjyNCwR4GRXU=
  file: release.tar.gz
  skip_cleanup: true
  on:
    repo: sonofmun/canonical-lat-test
    branch: master